# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Test轮播图' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'SnapKit', '~> 3.2.0'
  # Pods for Test轮播图

end
