# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'QMUIKit_Study' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for QMUIKit_Study

  pod "QMUIKit"
  pod "SDWebImage"
  pod "Masonry"
  target 'QMUIKit_StudyTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
