platform :ios, '9.0'
source 'https://github.com/CocoaPods/Specs.git'
source 'https://git-inner.cpgroupcloud.com/root/ModuleSpecs.git'

target 'QMUIKit_Study' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for QMUIKit_Study

  pod "QMUIKit", '4.1.3'
  pod "SDWebImage"
  pod "Masonry"
  pod 'ZDBaseModule','1.7.12'
  
  target 'QMUIKit_StudyTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
