# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'tt' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for tt

  pod 'YYWebImage'
  pod 'SDWebImage', '~> 4.0'
  pod 'FlyImage', '~>1.0'


  target 'ttTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ttUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
