# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SwiftUIControl' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'SnapKit', '~> 3.1.2'
  pod 'Alamofire', '~> 4.3'
  pod 'ReactiveCocoa', '~> 5.0.0'
  pod 'RealmSwift'
  pod 'ObjectMapper', '~> 2.2'
  # Pods for SwiftUIControl
  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['SWIFT_VERSION'] = '3.0'
      end
    end
  end
end
