# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'RealmUse' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'RealmSwift'
#  pod 'HandyJSON', '~> 1.8.0'

# pod 'ObjectMapper','~> 2.2'这个地址无效
  pod 'ObjectMapper', :git => 'https://github.com/Hearst-DD/ObjectMapper.git'

  # Pods for RealmUse

end
