# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RxSwift_Try' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'RxSwift', '~> 3.1'
  pod 'RxCocoa', '~> 3.1'
  pod 'RxDataSources', '~> 1.0'
  pod 'RxOptional', '~> 3.1'
  # Pods for RxSwift_Try

end
