# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ModelTransition' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ModelTransition
  pod 'YYModel'
  pod 'MJExtension'

  target 'ModelTransitionTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ModelTransitionUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
