# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WCDB_Study' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WCDB_Study
  pod 'WCDB'
  target 'WCDB_StudyTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
