# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
use_frameworks!
inhibit_all_warnings!

def common_pods
    
    pod 'ReactiveObjC'
    pod 'SocketRocket'
end

target 'RAC_Study' do
  
  common_pods
  
  target 'RAC_StudyTests' do
    inherit! :search_paths    
    common_pods
  end
end


