# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'RAC_Study' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RAC_Study
  pod 'ReactiveObjC'
  pod 'SocketRocket'
  target 'RAC_StudyTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
